export interface City {
  slug: string
  name: string
  state: string
  fullName: string
  population?: string
  industries: string[]
}

export const cities: Record<string, City> = {
  'new-york-ny': { slug: 'new-york-ny', name: 'New York', state: 'NY', fullName: 'New York, NY', population: '8.8 million', industries: ['Finance', 'Technology', 'Healthcare'] },
  'los-angeles-ca': { slug: 'los-angeles-ca', name: 'Los Angeles', state: 'CA', fullName: 'Los Angeles, CA', population: '4 million', industries: ['Technology', 'Healthcare', 'Manufacturing'] },
  'chicago-il': { slug: 'chicago-il', name: 'Chicago', state: 'IL', fullName: 'Chicago, IL', population: '2.7 million', industries: ['Finance', 'Technology', 'Education'] },
  'houston-tx': { slug: 'houston-tx', name: 'Houston', state: 'TX', fullName: 'Houston, TX', industries: ['Energy', 'Healthcare', 'Technology'] },
  'phoenix-az': { slug: 'phoenix-az', name: 'Phoenix', state: 'AZ', fullName: 'Phoenix, AZ', industries: ['Technology', 'Healthcare', 'Real Estate'] },
  'philadelphia-pa': { slug: 'philadelphia-pa', name: 'Philadelphia', state: 'PA', fullName: 'Philadelphia, PA', industries: ['Healthcare', 'Education', 'Finance'] },
  'san-antonio-tx': { slug: 'san-antonio-tx', name: 'San Antonio', state: 'TX', fullName: 'San Antonio, TX', industries: ['Healthcare', 'Technology', 'Education'] },
  'san-diego-ca': { slug: 'san-diego-ca', name: 'San Diego', state: 'CA', fullName: 'San Diego, CA', industries: ['Technology', 'Healthcare', 'Manufacturing'] },
  'dallas-tx': { slug: 'dallas-tx', name: 'Dallas', state: 'TX', fullName: 'Dallas, TX', industries: ['Finance', 'Technology', 'Healthcare'] },
  'san-jose-ca': { slug: 'san-jose-ca', name: 'San Jose', state: 'CA', fullName: 'San Jose, CA', industries: ['Technology', 'Manufacturing', 'Finance'] },
  'austin-tx': { slug: 'austin-tx', name: 'Austin', state: 'TX', fullName: 'Austin, TX', industries: ['Technology', 'Education', 'Healthcare'] },
  'jacksonville-fl': { slug: 'jacksonville-fl', name: 'Jacksonville', state: 'FL', fullName: 'Jacksonville, FL', industries: ['Logistics', 'Healthcare', 'Finance'] },
  'fort-worth-tx': { slug: 'fort-worth-tx', name: 'Fort Worth', state: 'TX', fullName: 'Fort Worth, TX', industries: ['Aerospace', 'Energy', 'Healthcare'] },
  'columbus-oh': { slug: 'columbus-oh', name: 'Columbus', state: 'OH', fullName: 'Columbus, OH', industries: ['Education', 'Healthcare', 'Technology'] },
  'indianapolis-in': { slug: 'indianapolis-in', name: 'Indianapolis', state: 'IN', fullName: 'Indianapolis, IN', industries: ['Manufacturing', 'Healthcare', 'Technology'] },
  'charlotte-nc': { slug: 'charlotte-nc', name: 'Charlotte', state: 'NC', fullName: 'Charlotte, NC', industries: ['Finance', 'Energy', 'Technology'] },
  'san-francisco-ca': { slug: 'san-francisco-ca', name: 'San Francisco', state: 'CA', fullName: 'San Francisco, CA', industries: ['Technology', 'Finance', 'Healthcare'] },
  'seattle-wa': { slug: 'seattle-wa', name: 'Seattle', state: 'WA', fullName: 'Seattle, WA', industries: ['Technology', 'Aerospace', 'Healthcare'] },
  'denver-co': { slug: 'denver-co', name: 'Denver', state: 'CO', fullName: 'Denver, CO', industries: ['Energy', 'Technology', 'Healthcare'] },
  'washington-dc': { slug: 'washington-dc', name: 'Washington', state: 'DC', fullName: 'Washington, D.C.', industries: ['Government', 'Technology', 'Healthcare'] },
  'nashville-tn': { slug: 'nashville-tn', name: 'Nashville', state: 'TN', fullName: 'Nashville, TN', industries: ['Healthcare', 'Manufacturing', 'Technology'] },
  'oklahoma-city-ok': { slug: 'oklahoma-city-ok', name: 'Oklahoma City', state: 'OK', fullName: 'Oklahoma City, OK', industries: ['Energy', 'Aerospace', 'Healthcare'] },
  'el-paso-tx': { slug: 'el-paso-tx', name: 'El Paso', state: 'TX', fullName: 'El Paso, TX', industries: ['Manufacturing', 'Healthcare', 'Technology'] },
  'boston-ma': { slug: 'boston-ma', name: 'Boston', state: 'MA', fullName: 'Boston, MA', industries: ['Education', 'Healthcare', 'Technology'] },
  'portland-or': { slug: 'portland-or', name: 'Portland', state: 'OR', fullName: 'Portland, OR', industries: ['Technology', 'Manufacturing', 'Healthcare'] },
  'las-vegas-nv': { slug: 'las-vegas-nv', name: 'Las Vegas', state: 'NV', fullName: 'Las Vegas, NV', industries: ['Tourism', 'Entertainment', 'Healthcare'] },
  'detroit-mi': { slug: 'detroit-mi', name: 'Detroit', state: 'MI', fullName: 'Detroit, MI', industries: ['Automotive', 'Manufacturing', 'Technology'] },
  'memphis-tn': { slug: 'memphis-tn', name: 'Memphis', state: 'TN', fullName: 'Memphis, TN', industries: ['Logistics', 'Healthcare', 'Manufacturing'] },
  'louisville-ky': { slug: 'louisville-ky', name: 'Louisville', state: 'KY', fullName: 'Louisville, KY', industries: ['Manufacturing', 'Healthcare', 'Logistics'] },
  'baltimore-md': { slug: 'baltimore-md', name: 'Baltimore', state: 'MD', fullName: 'Baltimore, MD', industries: ['Healthcare', 'Education', 'Manufacturing'] },
  'milwaukee-wi': { slug: 'milwaukee-wi', name: 'Milwaukee', state: 'WI', fullName: 'Milwaukee, WI', industries: ['Manufacturing', 'Finance', 'Healthcare'] },
  'albuquerque-nm': { slug: 'albuquerque-nm', name: 'Albuquerque', state: 'NM', fullName: 'Albuquerque, NM', industries: ['Technology', 'Healthcare', 'Education'] },
  'tucson-az': { slug: 'tucson-az', name: 'Tucson', state: 'AZ', fullName: 'Tucson, AZ', industries: ['Education', 'Healthcare', 'Technology'] },
  'fresno-ca': { slug: 'fresno-ca', name: 'Fresno', state: 'CA', fullName: 'Fresno, CA', industries: ['Agriculture', 'Healthcare', 'Education'] },
  'sacramento-ca': { slug: 'sacramento-ca', name: 'Sacramento', state: 'CA', fullName: 'Sacramento, CA', industries: ['Government', 'Healthcare', 'Technology'] },
  'kansas-city-mo': { slug: 'kansas-city-mo', name: 'Kansas City', state: 'MO', fullName: 'Kansas City, MO', industries: ['Logistics', 'Healthcare', 'Technology'] },
  'mesa-az': { slug: 'mesa-az', name: 'Mesa', state: 'AZ', fullName: 'Mesa, AZ', industries: ['Technology', 'Healthcare', 'Manufacturing'] },
  'raleigh-nc': { slug: 'raleigh-nc', name: 'Raleigh', state: 'NC', fullName: 'Raleigh, NC', industries: ['Technology', 'Healthcare', 'Finance'] },
  'omaha-ne': { slug: 'omaha-ne', name: 'Omaha', state: 'NE', fullName: 'Omaha, NE', industries: ['Finance', 'Technology', 'Healthcare'] },
  'miami-fl': { slug: 'miami-fl', name: 'Miami', state: 'FL', fullName: 'Miami, FL', industries: ['Tourism', 'Finance', 'Healthcare'] },
  'oakland-ca': { slug: 'oakland-ca', name: 'Oakland', state: 'CA', fullName: 'Oakland, CA', industries: ['Technology', 'Healthcare', 'Manufacturing'] },
  'minneapolis-mn': { slug: 'minneapolis-mn', name: 'Minneapolis', state: 'MN', fullName: 'Minneapolis, MN', industries: ['Healthcare', 'Finance', 'Technology'] },
  'tulsa-ok': { slug: 'tulsa-ok', name: 'Tulsa', state: 'OK', fullName: 'Tulsa, OK', industries: ['Energy', 'Healthcare', 'Manufacturing'] },
  'wichita-ks': { slug: 'wichita-ks', name: 'Wichita', state: 'KS', fullName: 'Wichita, KS', industries: ['Manufacturing', 'Healthcare', 'Aviation'] },
  'new-orleans-la': { slug: 'new-orleans-la', name: 'New Orleans', state: 'LA', fullName: 'New Orleans, LA', industries: ['Tourism', 'Energy', 'Healthcare'] },
  'arlington-tx': { slug: 'arlington-tx', name: 'Arlington', state: 'TX', fullName: 'Arlington, TX', industries: ['Technology', 'Healthcare', 'Entertainment'] },
  'cleveland-oh': { slug: 'cleveland-oh', name: 'Cleveland', state: 'OH', fullName: 'Cleveland, OH', industries: ['Healthcare', 'Manufacturing', 'Finance'] },
  'bakersfield-ca': { slug: 'bakersfield-ca', name: 'Bakersfield', state: 'CA', fullName: 'Bakersfield, CA', industries: ['Agriculture', 'Energy', 'Healthcare'] },
  'tampa-fl': { slug: 'tampa-fl', name: 'Tampa', state: 'FL', fullName: 'Tampa, FL', industries: ['Healthcare', 'Finance', 'Technology'] },
  'aurora-co': { slug: 'aurora-co', name: 'Aurora', state: 'CO', fullName: 'Aurora, CO', industries: ['Healthcare', 'Technology', 'Manufacturing'] },
  'honolulu-hi': { slug: 'honolulu-hi', name: 'Honolulu', state: 'HI', fullName: 'Honolulu, HI', industries: ['Tourism', 'Healthcare', 'Military'] },
  'anaheim-ca': { slug: 'anaheim-ca', name: 'Anaheim', state: 'CA', fullName: 'Anaheim, CA', industries: ['Tourism', 'Manufacturing', 'Healthcare'] },
  'santa-ana-ca': { slug: 'santa-ana-ca', name: 'Santa Ana', state: 'CA', fullName: 'Santa Ana, CA', industries: ['Manufacturing', 'Healthcare', 'Retail'] },
  'corpus-christi-tx': { slug: 'corpus-christi-tx', name: 'Corpus Christi', state: 'TX', fullName: 'Corpus Christi, TX', industries: ['Energy', 'Tourism', 'Healthcare'] },
  'riverside-ca': { slug: 'riverside-ca', name: 'Riverside', state: 'CA', fullName: 'Riverside, CA', industries: ['Healthcare', 'Education', 'Manufacturing'] },
  'st-louis-mo': { slug: 'st-louis-mo', name: 'St. Louis', state: 'MO', fullName: 'St. Louis, MO', industries: ['Healthcare', 'Manufacturing', 'Finance'] },
  'lexington-ky': { slug: 'lexington-ky', name: 'Lexington', state: 'KY', fullName: 'Lexington, KY', industries: ['Healthcare', 'Manufacturing', 'Education'] },
  'pittsburgh-pa': { slug: 'pittsburgh-pa', name: 'Pittsburgh', state: 'PA', fullName: 'Pittsburgh, PA', industries: ['Healthcare', 'Technology', 'Finance'] },
  'stockton-ca': { slug: 'stockton-ca', name: 'Stockton', state: 'CA', fullName: 'Stockton, CA', industries: ['Agriculture', 'Manufacturing', 'Healthcare'] },
  'cincinnati-oh': { slug: 'cincinnati-oh', name: 'Cincinnati', state: 'OH', fullName: 'Cincinnati, OH', industries: ['Manufacturing', 'Healthcare', 'Finance'] },
  'anchorage-ak': { slug: 'anchorage-ak', name: 'Anchorage', state: 'AK', fullName: 'Anchorage, AK', industries: ['Energy', 'Healthcare', 'Tourism'] },
  'henderson-nv': { slug: 'henderson-nv', name: 'Henderson', state: 'NV', fullName: 'Henderson, NV', industries: ['Healthcare', 'Manufacturing', 'Technology'] },
  'greensboro-nc': { slug: 'greensboro-nc', name: 'Greensboro', state: 'NC', fullName: 'Greensboro, NC', industries: ['Manufacturing', 'Healthcare', 'Education'] },
  'plano-tx': { slug: 'plano-tx', name: 'Plano', state: 'TX', fullName: 'Plano, TX', industries: ['Technology', 'Healthcare', 'Finance'] },
  'newark-nj': { slug: 'newark-nj', name: 'Newark', state: 'NJ', fullName: 'Newark, NJ', industries: ['Transportation', 'Healthcare', 'Finance'] },
  'lincoln-ne': { slug: 'lincoln-ne', name: 'Lincoln', state: 'NE', fullName: 'Lincoln, NE', industries: ['Education', 'Healthcare', 'Insurance'] },
  'orlando-fl': { slug: 'orlando-fl', name: 'Orlando', state: 'FL', fullName: 'Orlando, FL', industries: ['Tourism', 'Technology', 'Healthcare'] },
  'irvine-ca': { slug: 'irvine-ca', name: 'Irvine', state: 'CA', fullName: 'Irvine, CA', industries: ['Technology', 'Healthcare', 'Education'] },
  'toledo-oh': { slug: 'toledo-oh', name: 'Toledo', state: 'OH', fullName: 'Toledo, OH', industries: ['Manufacturing', 'Healthcare', 'Education'] },
  'jersey-city-nj': { slug: 'jersey-city-nj', name: 'Jersey City', state: 'NJ', fullName: 'Jersey City, NJ', industries: ['Finance', 'Healthcare', 'Technology'] },
  'chula-vista-ca': { slug: 'chula-vista-ca', name: 'Chula Vista', state: 'CA', fullName: 'Chula Vista, CA', industries: ['Manufacturing', 'Healthcare', 'Retail'] },
  'buffalo-ny': { slug: 'buffalo-ny', name: 'Buffalo', state: 'NY', fullName: 'Buffalo, NY', industries: ['Healthcare', 'Education', 'Manufacturing'] },
  'durham-nc': { slug: 'durham-nc', name: 'Durham', state: 'NC', fullName: 'Durham, NC', industries: ['Healthcare', 'Technology', 'Education'] },
  'st-petersburg-fl': { slug: 'st-petersburg-fl', name: 'St. Petersburg', state: 'FL', fullName: 'St. Petersburg, FL', industries: ['Healthcare', 'Finance', 'Tourism'] },
  'laredo-tx': { slug: 'laredo-tx', name: 'Laredo', state: 'TX', fullName: 'Laredo, TX', industries: ['Transportation', 'Retail', 'Healthcare'] },
  'lubbock-tx': { slug: 'lubbock-tx', name: 'Lubbock', state: 'TX', fullName: 'Lubbock, TX', industries: ['Agriculture', 'Healthcare', 'Education'] },
  'madison-wi': { slug: 'madison-wi', name: 'Madison', state: 'WI', fullName: 'Madison, WI', industries: ['Education', 'Healthcare', 'Technology'] },
  'gilbert-az': { slug: 'gilbert-az', name: 'Gilbert', state: 'AZ', fullName: 'Gilbert, AZ', industries: ['Technology', 'Healthcare', 'Education'] },
  'norfolk-va': { slug: 'norfolk-va', name: 'Norfolk', state: 'VA', fullName: 'Norfolk, VA', industries: ['Military', 'Healthcare', 'Transportation'] },
  'reno-nv': { slug: 'reno-nv', name: 'Reno', state: 'NV', fullName: 'Reno, NV', industries: ['Tourism', 'Technology', 'Healthcare'] },
  'winston-salem-nc': { slug: 'winston-salem-nc', name: 'Winston-Salem', state: 'NC', fullName: 'Winston-Salem, NC', industries: ['Healthcare', 'Manufacturing', 'Education'] },
  'glendale-az': { slug: 'glendale-az', name: 'Glendale', state: 'AZ', fullName: 'Glendale, AZ', industries: ['Healthcare', 'Retail', 'Manufacturing'] },
  'hialeah-fl': { slug: 'hialeah-fl', name: 'Hialeah', state: 'FL', fullName: 'Hialeah, FL', industries: ['Manufacturing', 'Healthcare', 'Retail'] },
  'boise-id': { slug: 'boise-id', name: 'Boise', state: 'ID', fullName: 'Boise, ID', industries: ['Technology', 'Healthcare', 'Manufacturing'] },
  'richmond-va': { slug: 'richmond-va', name: 'Richmond', state: 'VA', fullName: 'Richmond, VA', industries: ['Finance', 'Healthcare', 'Government'] },
  'spokane-wa': { slug: 'spokane-wa', name: 'Spokane', state: 'WA', fullName: 'Spokane, WA', industries: ['Healthcare', 'Education', 'Manufacturing'] },
  'des-moines-ia': { slug: 'des-moines-ia', name: 'Des Moines', state: 'IA', fullName: 'Des Moines, IA', industries: ['Insurance', 'Finance', 'Healthcare'] },
  'atlanta-ga': { slug: 'atlanta-ga', name: 'Atlanta', state: 'GA', fullName: 'Atlanta, GA', industries: ['Technology', 'Finance', 'Healthcare', 'Transportation'] },
  'salt-lake-city-ut': { slug: 'salt-lake-city-ut', name: 'Salt Lake City', state: 'UT', fullName: 'Salt Lake City, UT', industries: ['Technology', 'Finance', 'Healthcare'] },
  'colorado-springs-co': { slug: 'colorado-springs-co', name: 'Colorado Springs', state: 'CO', fullName: 'Colorado Springs, CO', industries: ['Military', 'Technology', 'Healthcare'] },
  'fort-lauderdale-fl': { slug: 'fort-lauderdale-fl', name: 'Fort Lauderdale', state: 'FL', fullName: 'Fort Lauderdale, FL', industries: ['Tourism', 'Marine', 'Healthcare'] },
  'long-beach-ca': { slug: 'long-beach-ca', name: 'Long Beach', state: 'CA', fullName: 'Long Beach, CA', industries: ['Transportation', 'Healthcare', 'Manufacturing'] },
  'virginia-beach-va': { slug: 'virginia-beach-va', name: 'Virginia Beach', state: 'VA', fullName: 'Virginia Beach, VA', industries: ['Tourism', 'Military', 'Healthcare'] },
  'rochester-ny': { slug: 'rochester-ny', name: 'Rochester', state: 'NY', fullName: 'Rochester, NY', industries: ['Technology', 'Healthcare', 'Education'] },
  'chandler-az': { slug: 'chandler-az', name: 'Chandler', state: 'AZ', fullName: 'Chandler, AZ', industries: ['Technology', 'Healthcare', 'Manufacturing'] },
  'scottsdale-az': { slug: 'scottsdale-az', name: 'Scottsdale', state: 'AZ', fullName: 'Scottsdale, AZ', industries: ['Tourism', 'Healthcare', 'Technology'] },
  'fremont-ca': { slug: 'fremont-ca', name: 'Fremont', state: 'CA', fullName: 'Fremont, CA', industries: ['Technology', 'Manufacturing', 'Healthcare'] },
  'irving-tx': { slug: 'irving-tx', name: 'Irving', state: 'TX', fullName: 'Irving, TX', industries: ['Technology', 'Finance', 'Healthcare'] },
}

export function getCity(slug: string): City | undefined {
  return cities[slug]
}

export const citySlugs: string[] = Object.keys(cities)


